CREATE TABLE DIM_SEDE (
    SK_SEDE INT PRIMARY KEY,
    COD_PAIS NUMERIC,
    NB_PAIS VARCHAR(100),
    COD_CIUDAD NUMERIC,
    NB_CIUDAD VARCHAR(100),
    COD_SEDE NUMERIC,
    NB_SEDE VARCHAR(100)
);

CREATE TABLE DIM_LEYENDA (
    SK_LEYENDA INT PRIMARY KEY,
    COD_LEYENDA NUMERIC,
    NB_LEYENDA VARCHAR(100)
);

CREATE TABLE DIM_VISITANTE (
    SK_VISITANTE INT PRIMARY KEY,
    COD_VISITANTE NUMERIC,
    CEDULA NUMERIC,
    NB_VISITANTE VARCHAR(100),
    SEXO VARCHAR(100),
    EMAIL VARCHAR(100)
);

CREATE TABLE DIM_TIEMPO (
    SK_TIEMPO INT PRIMARY KEY,
    COD_ANIO NUMERIC,
    COD_TRIMESTRE NUMERIC,
    DES_TRIMESTRE VARCHAR(100),
    COD_MES NUMERIC,
    DESC_MES VARCHAR(20),
    DESC_MES_CORTAVARCHA2 VARCHAR(20),
    COD_SEMANA NUMERIC,
    COD_DIA_ANIO NUMERIC,
    COD_DIA_MES NUMERIC,
    COD_DIA_SEMANA NUMERIC,
    DESC_DIA_SEMANA VARCHAR(100),
    FECHA DATE
);

CREATE TABLE DIM_CLIENTE (
    SK_CLIENTE INT PRIMARY KEY,
    COD_CLIENTE NUMERIC,
    CI_RIF VARCHAR(100),
    NB_CLIENTE VARCHAR(100),
    TELEFONO VARCHAR(100),
    DIRECCION VARCHAR(100),
    EMAIL VARCHAR(100)
);

CREATE TABLE DIM_CATEGORIA (
    SK_CATEGORIA INT PRIMARY KEY,
    COD_SUBCATEGORIA NUMERIC,
    NB_SUBCATEGORIA VARCHAR(100),
    COD_CATEGORIA NUMERIC,
    NB_CATEGORIA VARCHAR(100)
);

CREATE TABLE DIM_EVENTO (
    SK_EVENTO INT PRIMARY KEY,
    COD_TIPO_EVENTO NUMERIC,
    NB_TIPO_EVENTO VARCHAR(100),
    COD_EVENTO NUMERIC,
    NB_EVENTO VARCHAR(100),
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE DIM_TIPO_STAND (
    SK_TIPO_STAND INT PRIMARY KEY,
    COD_TIPO_STAND NUMERIC,
    NB_TIPO_STAND VARCHAR(100)
);

CREATE TABLE FACT_EVENTO (
    SK_EVENTO INT REFERENCES DIM_EVENTO(SK_EVENTO),
    SK_SEDE INT REFERENCES DIM_SEDE(SK_SEDE),
    SK_FEC_EVENTO INT REFERENCES DIM_TIEMPO(SK_TIEMPO),
    CANTIDAD_EVENTO NUMERIC,
    CANTIDAD_ESTIM_VISITANTES NUMERIC,
    META_INGRESO NUMERIC(15,4),
    PRIMARY KEY (SK_EVENTO, SK_SEDE, SK_FEC_EVENTO)
);

CREATE TABLE FACT_VISITA (
    SK_EVENTO INT REFERENCES DIM_EVENTO(SK_EVENTO),
    SK_VISITANTE INT REFERENCES DIM_VISITANTE(SK_VISITANTE),
    SK_FEC_ENTRADA INT REFERENCES DIM_TIEMPO(SK_TIEMPO),
    SK_LEYENDA_ESTRELLAS INT REFERENCES DIM_LEYENDA(SK_LEYENDA),
    NUM_ENTRADA NUMERIC,
    HORA_ENTRADA TIMESTAMP,
    CANTIDAD_VISITA NUMERIC,
    CALIFICACION VARCHAR(10),
    RECOMIENDA_AMIGO VARCHAR(100),
    PRIMARY KEY (SK_EVENTO, SK_VISITANTE, SK_FEC_ENTRADA, NUM_ENTRADA)
);

CREATE TABLE FACT_EVENTO_STAND (
    SK_EVENTO INT REFERENCES DIM_EVENTO(SK_EVENTO),
    SK_TIPO_STAND INT REFERENCES DIM_TIPO_STAND(SK_TIPO_STAND),
    CANTIDAD_ESTIMADA NUMERIC,
    MT2 NUMERIC(15,4),
    PRECIO NUMERIC(15,4),
    PRIMARY KEY (SK_EVENTO, SK_TIPO_STAND)
);

CREATE TABLE FACT_ALQUILER (
    SK_EVENTO INT REFERENCES DIM_EVENTO(SK_EVENTO),
    SK_CLIENTE INT REFERENCES DIM_CLIENTE(SK_CLIENTE),
    SK_FEC_ALQUILER INT REFERENCES DIM_TIEMPO(SK_TIEMPO),
    SK_TIPO_STAND INT REFERENCES DIM_TIPO_STAND(SK_TIPO_STAND),
    SK_CATEGORIA INT REFERENCES DIM_CATEGORIA(SK_CATEGORIA),
    NUM_CONTRATO NUMERIC,
    NUM_STAND NUMERIC,
    MT2 NUMERIC(15,4),
    MONTO NUMERIC(15,4),
    CANTIDAD NUMERIC,
    PRIMARY KEY (SK_EVENTO, SK_CLIENTE, SK_FEC_ALQUILER, NUM_CONTRATO, NUM_STAND)
);